FROM alpine:3.17.0
RUN apk add ruby-full ruby-dev build-base --no-cache \
    && gem install bundler

ENV APP_HOME /app
#RUN mkdir $APP_HOME

WORKDIR $APP_HOME
#ADD Gemfile* $APP_HOME/
ADD . $APP_HOME
RUN bundle install
#ADD . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
